In [10]:
# Ejercicio 1: Crear un array de 10 elementos con ceros.
import numpy as np
array_10_ceros = np.zeros(10)
print("Ejercicio 1:\n", array_10_ceros)

Ejercicio 1:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
# Ejercicio 2: Genera un array con los números del 1 al 20.
import numpy as np
array_num_1_al_20 = np.arange(1, 21)
print("Ejercicio 2:\n", array_num_1_al_20)

Ejercicio 2:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [12]:
# Ejercicio 3: Crea un array con los números pares del 2 al 50.
import numpy as np
array_pares_2_al_50 = np.arange(2, 51, 2)
print("Ejercicio 3:\n", array_pares_2_al_50)

Ejercicio 3:
 [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


In [5]:
# Ejercicio 5: Crea una matriz de 4x4 con valores aleatorios entre 0 y 1.
import numpy as np
matriz_4x4_aleatorios_entre_0_y_1 = np.random.rand(4, 4)
print("Ejercicio 5:\n", matriz_4x4_aleatorios_entre_0_y_1)

Ejercicio 5:
 [[0.88332232 0.69143072 0.06604384 0.90401275]
 [0.53333266 0.85251135 0.78086496 0.98012656]
 [0.46715956 0.56038818 0.71538619 0.97299322]
 [0.3460406  0.70638582 0.66312686 0.27379269]]


In [13]:
# Ejercicio 6: Realiza la suma elemento a elemento de los arrays a=[1,2,3], b=[4,5,6].
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
suma = a + b
print("Ejercicio 6:\n", suma)

Ejercicio 6:
 [5 7 9]


In [7]:
# Ejercicio 7: Multiplica dos matrices 3x3 de enteros aleatorios entre 1 y 10.
import numpy as np
matriz3x3_1 = np.random.randint(1, 11, (3, 3))
matriz3x3_2 = np.random.randint(1, 11, (3, 3))
producto_matriz3x3 = np.dot(matriz3x3_1, matriz3x3_2)
print("Ejercicio 7 - Matriz 1:\n", matriz3x3_1)
print("Ejercicio 7 - Matriz 2:\n", matriz3x3_2)
print("Ejercicio 7 - Producto:\n", producto_matriz3x3)

Ejercicio 7 - Matriz 1:
 [[3 4 3]
 [8 7 4]
 [9 4 9]]
Ejercicio 7 - Matriz 2:
 [[ 5  2  9]
 [ 3 10  6]
 [10  4  1]]
Ejercicio 7 - Producto:
 [[ 57  58  54]
 [101 102 118]
 [147  94 114]]


In [14]:
# Ejercicio 8: Crea un array de 15 valores aleatorios entre 1 y 100 e imprime su máximo, mínimo y promedio.
import numpy as np
array_15_aleatorios_entre_1_y_100 = np.random.randint(1, 101, 15)
maximo = np.max(array_15_aleatorios_entre_1_y_100)
minimo = np.min(array_15_aleatorios_entre_1_y_100)
promedio = np.mean(array_15_aleatorios_entre_1_y_100)

print("Ejercicio 8 - array:\n", array_15_aleatorios_entre_1_y_100)
print("Ejercicio 8 - Máximo:", maximo)
print("Ejercicio 8 - Mínimo:", minimo)
print("Ejercicio 8 - Promedio:", promedio)


Ejercicio 8 - array:
 [59 81 67 85 66 10 38 12  1 85 54 51 44 13 17]
Ejercicio 8 - Máximo: 85
Ejercicio 8 - Mínimo: 1
Ejercicio 8 - Promedio: 45.53333333333333


In [15]:
# Ejercicio 9: Genera una matriz 5x5 con valores del 1 al 25 y extrae su diagonal.
import numpy as np
matriz_5x5_aleatorios_1_al_25 = np.arange(1, 26).reshape(5, 5)
diagonal = np.diag(matriz_5x5_aleatorios_1_al_25)

print("Ejercicio 9 - matriz:\n", matriz_5x5_aleatorios_1_al_25)
print("Ejercicio 9 - Diagonal:\n", diagonal)


Ejercicio 9 - matriz:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Ejercicio 9 - Diagonal:
 [ 1  7 13 19 25]


In [16]:
# Ejercicio 10: Dada una matriz 5x5 de enteros aleatorios entre 1 y 20, calcula la suma de cada fila y columna.
import numpy as np
matriz_5x5_aleatorios_int_1_al_20 = np.random.randint(1, 21, (5, 5))
suma_filas = matriz_5x5_aleatorios_int_1_al_20.sum(axis=1)
suma_columnas = matriz_5x5_aleatorios_int_1_al_20.sum(axis=0)

print("Ejercicio 10 - matriz:\n", matriz_5x5_aleatorios_int_1_al_20)
print("Ejercicio 10 - Suma de filas:", suma_filas)
print("Ejercicio 10 - Suma de columnas:", suma_columnas)

Ejercicio 10 - matriz:
 [[19  9 17 20 14]
 [16 15 12  1  5]
 [11  1 16 17  2]
 [ 8 11 13 13  5]
 [13  2  1 12 13]]
Ejercicio 10 - Suma de filas: [79 49 47 50 41]
Ejercicio 10 - Suma de columnas: [67 38 59 63 39]
